"""empty message

Revision ID: 0a239f692c3c
Revises: 
Create Date: 2021-04-11 19:13:53.904403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a239f692c3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enc_sum',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender', sa.INTEGER(), nullable=False),
    sa.Column('val', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enc_sum')
    # ### end Alembic commands ###
