"""empty message

Revision ID: 3abee445e0cb
Revises: 0a239f692c3c
Create Date: 2021-04-11 20:04:14.132556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abee445e0cb'
down_revision = '0a239f692c3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enc_sum',
    sa.Column('ID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender', sa.INTEGER(), nullable=False),
    sa.Column('val', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('sender')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enc_sum')
    # ### end Alembic commands ###
