"""empty message

Revision ID: e72d8ed9fdbc
Revises: 
Create Date: 2021-04-13 09:55:08.624379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e72d8ed9fdbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voter', sa.Column('finished', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voter', 'finished')
    # ### end Alembic commands ###
